ci:
  autofix_prs: false
  autoupdate_schedule: "quarterly"
  skip: [poetry-lock, poetry-export]

default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.0"
    hooks:
      - id: poetry-check
        name: check poetry (poetry-check)
        always_run: true

      - id: poetry-lock
        name: lock poetry (poetry-lock)
        files: "pyproject.toml"

      - id: poetry-export
        name: export poetry docs (poetry-export)
        args: ["--only=docs", "-f", "requirements.txt", "-o", "docs/requirements_docs.txt"]
        files: "pyproject.toml|poetry.lock"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
        name: check case conflict (check-case-conflict)
        always_run: true

      - id: check-merge-conflict
        name: check merge conflict (check-merge-conflict)
        always_run: true

      - id: check-yaml
        name: check yaml (check-yaml)
        exclude: mkdocs.yaml
        stages: [commit, push]
        types: [yaml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: sort imports (isort)

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
        name: format python code (black)

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: check code style (flake8)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        name: check types (mypy)
        additional_dependencies: [types-requests]
        require_serial: true

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        name: format files (prettier)

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        name: upgrade pre-commit (pyupgrade)
        args: [--py310-plus]
