name: Run Pytest

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies using Poetry
        run: poetry install
      - name: Run tests
        run: poetry run pytest
      - name: Check code coverage
        run: poetry run pytest --cov --cov-fail-under=80
